In [4]:
!pip install pandas

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in .\.venv\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd

Series = one Dimention,

In [7]:
l = [2,43,21,83,19,32]

series = pd.Series(l)
series

0     2
1    43
2    21
3    83
4    19
5    32
dtype: int64

In [8]:
type(series)

pandas.Series

In [10]:
dict = {'a':2,'b':43,'c':21,'d':83,'e':19,'f':32}

res = pd.Series(dict)
res

a     2
b    43
c    21
d    83
e    19
f    32
dtype: int64

In [13]:
for i in res:
    print(i)

2
43
21
83
19
32

In [14]:
res['a']

np.int64(2)

In [15]:
res['a' : 'd']

a     2
b    43
c    21
d    83
dtype: int64

Dataframe = more than one Dimention (usually 2d)

In [17]:
data = [["abc",1],['def',2],['ghi',3],['hij'],['kim',5]]
data_df = pd.DataFrame(data)
data_df

     0    1
0  abc  1.0
1  def  2.0
2  ghi  3.0
3  hij  NaN
4  kim  5.0

In [30]:
data_df.columns = ['Alphabhet','Numbers']

In [31]:
data_df

  Alphabhet  Numbers
0       abc      1.0
1       def      2.0
2       ghi      3.0
3       hij      NaN
4       kim      5.0

In [32]:
data_df.columns

Index(['Alphabhet', 'Numbers'], dtype='str')

In [35]:
data_df.rename({'Alphabhet' : 'Alpha'} , axis = 1 , inplace= True )

In [36]:
data_df

  Alpha  Numbers
0   abc      1.0
1   def      2.0
2   ghi      3.0
3   hij      NaN
4   kim      5.0

In [37]:
df = pd.read_csv('titanic.csv')

In [39]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [40]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q